# Production Docker Compose for Managed Database
# Use this configuration when you have a managed database from Render/AWS

version: '3.8'

services:
  # Multi-Tenant Authentication Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-tenant-auth-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Application Settings
      APP_NAME: "Multi-Tenant Authentication Service"
      APP_VERSION: "1.0.0"
      ENVIRONMENT: "production"
      DEBUG: "false"
      HOST: "0.0.0.0"
      PORT: "8000"
      
      # Keycloak Configuration
      KEYCLOAK_SERVER_URL: "http://keycloak:8080"
      KEYCLOAK_STARTUP_CHECK_ENABLED: "true"
      KEYCLOAK_STARTUP_CHECK_RETRIES: "5"
      KEYCLOAK_STARTUP_CHECK_RETRY_DELAY: "10"
      KEYCLOAK_STARTUP_CHECK_EXIT_ON_FAILURE: "true"
      
      # Admin credentials removed for security - now passed per-request in admin APIs
      # KEYCLOAK_ADMIN_USERNAME: "${KEYCLOAK_ADMIN_USER}"
      # KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      
      # Security Settings
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      REFRESH_TOKEN_EXPIRE_DAYS: "7"
      
      # CORS Settings
      CORS_ORIGINS: "${CORS_ORIGINS}"
      CORS_ALLOW_CREDENTIALS: "true"
      CORS_ALLOW_METHODS: '["*"]'
      CORS_ALLOW_HEADERS: '["*"]'
      
      # Logging
      LOG_LEVEL: "INFO"
      LOG_FORMAT: "json"
    networks:
      - auth-network
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Keycloak Identity Provider (with managed database)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    restart: unless-stopped
    command: start --optimized
    environment:
      # Keycloak Admin
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN_USER}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      
      # Managed Database Configuration
      KC_DB: postgres
      KC_DB_URL: "${KC_DB_URL}"  # Your managed database URL
      KC_DB_USERNAME: "${KC_DB_USERNAME}"
      KC_DB_PASSWORD: "${KC_DB_PASSWORD}"
      
      # Production Settings
      KC_HOSTNAME: "${KC_HOSTNAME}"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: "edge"
      
      # Performance Settings
      KC_CACHE: "ispn"
      KC_CACHE_STACK: "kubernetes"
      
      # Logging
      KC_LOG_LEVEL: "INFO"
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - keycloak-data:/opt/keycloak/data

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates directory
    networks:
      - auth-network
    depends_on:
      - auth-service
      - keycloak

networks:
  auth-network:
    driver: bridge
    name: multi-tenant-auth-network

volumes:
  keycloak-data:
    name: keycloak-data
